defmodule Scriber.Level do
  @moduledoc """
  One stratum of the Lattice: a grid of tiles plus the fixtures placed in it.

  A level is generated by `build/2` from a generator and a depth, and is thereafter
  immutable except through `unseal/1`. Entities, items and the player live in `Scriber.Game`,
  not here.

  Tiles are held in a map keyed by `{x, y}`; a coordinate with no entry reads as `:rock`.
  Every stratum is the same size, given by the struct's `:width` and `:height`.

  ## What is in a stratum

  Rooms joined by L-shaped corridors, and three fixtures:

    * a **console** at `:console`, in a room between the first and the last — where the gate
      is opened and shards are spent, see `Scriber.Console`
    * a **gate** at `:gate`, in the last room placed — the way down, solid until `unseal/1`
      turns it into a `:stair`
    * the player's **spawn** at `:spawn`, the centre of the first room placed

  A gate cannot be opened from here; `Scriber.Console` accepts the access code and the caller
  then invokes `unseal/1`.

  ## Example

      {level, rng} = Scriber.Level.build(Cauldron2D.Rng.new(7), 1)
      Scriber.Level.at(level, level.spawn)
      #=> :floor
  """

  alias Cauldron2D.Rng

  @type point :: {integer(), integer()}
  @type tile :: :rock | :wall | :floor | :door | :console | :gate | :stair

  @type t :: %__MODULE__{
          width: pos_integer(),
          height: pos_integer(),
          depth: pos_integer(),
          tiles: %{point() => tile()},
          rooms: [rect()],
          spawn: point(),
          console: point() | nil,
          gate: point() | nil,
          unsealed?: boolean()
        }

  @type rect :: %{x: integer(), y: integer(), width: pos_integer(), height: pos_integer()}

  defstruct [
    :width,
    :height,
    :depth,
    :spawn,
    :console,
    :gate,
    tiles: %{},
    rooms: [],
    unsealed?: false
  ]

  @width 56
  @height 30
  @room_attempts 90
  @min_room 5
  @max_room 11
  @doors_from 2

  @doc """
  Generate a stratum at `depth`, returning `{level, rng}` with the generator advanced.

  Rooms are placed by rejection: a fixed number of candidate rectangles are tried and each is
  kept only if it clears every room already placed by one tile. Rooms are then joined in
  placement order by L-shaped corridors, fixtures are placed, and every floor tile with no
  neighbour gets a `:wall`. From stratum #{@doors_from} the corridor tile at each room's
  threshold is a `:door`, which blocks sight until it is opened by walking through it.
  Generation never fails — a crowded draw yields fewer rooms, and
  the degenerate case of no rooms at all yields a level with `spawn: {1, 1}` and no gate or
  console.

  The same `rng` and `depth` always produce the same level.
  """
  @spec build(Rng.t(), pos_integer()) :: {t(), Rng.t()}
  def build(rng, depth) do
    {rooms, rng} = place_rooms(rng)
    tiles = rooms |> carve_rooms() |> carve_corridors(rooms)

    level =
      %__MODULE__{width: @width, height: @height, depth: depth, rooms: rooms, tiles: tiles}
      |> doors()
      |> place_fixtures()
      |> walls()

    {level, rng}
  end

  defp place_rooms(rng) do
    Enum.reduce(1..@room_attempts//1, {[], rng}, fn _, {rooms, rng} ->
      {candidate, rng} = random_room(rng)

      if Enum.any?(rooms, &overlaps?(&1, candidate)) do
        {rooms, rng}
      else
        {rooms ++ [candidate], rng}
      end
    end)
  end

  defp random_room(rng) do
    {width, rng} = Rng.between(rng, @min_room, @max_room)
    {height, rng} = Rng.between(rng, @min_room - 1, @max_room - 3)
    {x, rng} = Rng.between(rng, 1, @width - width - 2)
    {y, rng} = Rng.between(rng, 1, @height - height - 2)
    {%{x: x, y: y, width: width, height: height}, rng}
  end

  defp overlaps?(a, b) do
    a.x - 1 <= b.x + b.width and b.x - 1 <= a.x + a.width and
      a.y - 1 <= b.y + b.height and b.y - 1 <= a.y + a.height
  end

  defp carve_rooms(rooms) do
    for room <- rooms,
        x <- room.x..(room.x + room.width - 1)//1,
        y <- room.y..(room.y + room.height - 1)//1,
        into: %{} do
      {{x, y}, :floor}
    end
  end

  defp carve_corridors(tiles, rooms) do
    rooms
    |> Enum.chunk_every(2, 1, :discard)
    |> Enum.reduce(tiles, fn [a, b], acc -> corridor(acc, center(a), center(b)) end)
  end

  defp corridor(tiles, {x1, y1}, {x2, y2}) do
    tiles
    |> carve_line(x1..x2//step(x1, x2), fn x -> {x, y1} end)
    |> carve_line(y1..y2//step(y1, y2), fn y -> {x2, y} end)
  end

  defp carve_line(tiles, range, to_point) do
    Enum.reduce(range, tiles, fn n, acc -> Map.put_new(acc, to_point.(n), :floor) end)
  end

  defp step(a, b) when a <= b, do: 1
  defp step(_a, _b), do: -1

  @doc "The centre tile of a room rectangle, rounding down on both axes."
  @spec center(rect()) :: point()
  def center(room), do: {room.x + div(room.width, 2), room.y + div(room.height, 2)}

  defp place_fixtures(%__MODULE__{rooms: []} = level) do
    %{level | spawn: {1, 1}}
  end

  defp place_fixtures(%__MODULE__{rooms: rooms} = level) do
    first = hd(rooms)
    last = List.last(rooms)
    console_room = console_room(rooms)

    gate = center(last)
    console = center(console_room)

    tiles = level.tiles |> Map.put(gate, :gate) |> Map.put(console, :console)

    %{level | spawn: center(first), gate: gate, console: console, tiles: tiles}
  end

  defp console_room([only]), do: only
  defp console_room(rooms), do: rooms |> Enum.drop(1) |> Enum.drop(-1) |> pick_middle(rooms)

  defp pick_middle([], rooms), do: hd(rooms)
  defp pick_middle(middle, _rooms), do: Enum.at(middle, div(length(middle), 2))

  defp doors(%__MODULE__{depth: depth} = level) when depth < @doors_from, do: level

  defp doors(%__MODULE__{rooms: rooms, tiles: tiles} = level) do
    thresholds =
      for {point, :floor} <- tiles,
          not Enum.any?(rooms, &inside?(&1, point)),
          Enum.any?(neighbours4(point), fn beside -> Enum.any?(rooms, &inside?(&1, beside)) end),
          do: point

    %{level | tiles: Enum.reduce(thresholds, tiles, &Map.put(&2, &1, :door))}
  end

  defp inside?(room, {x, y}),
    do: x >= room.x and x < room.x + room.width and y >= room.y and y < room.y + room.height

  defp neighbours4({x, y}), do: [{x + 1, y}, {x - 1, y}, {x, y + 1}, {x, y - 1}]

  @doc "The level with the door at `point` opened: a floor tile, sight passing through. Any other tile is left alone."
  @spec open(t(), point()) :: t()
  def open(%__MODULE__{tiles: tiles} = level, point) do
    case Map.get(tiles, point) do
      :door -> %{level | tiles: Map.put(tiles, point, :floor)}
      _other -> level
    end
  end

  defp walls(%__MODULE__{tiles: tiles} = level) do
    filled =
      tiles
      |> Map.keys()
      |> Enum.flat_map(&neighbours8/1)
      |> Enum.reduce(tiles, fn point, acc -> Map.put_new(acc, point, :wall) end)
      |> Map.reject(fn {{x, y}, _tile} -> x < 0 or y < 0 or x >= @width or y >= @height end)

    %{level | tiles: filled}
  end

  defp neighbours8({x, y}) do
    for dx <- -1..1//1, dy <- -1..1//1, {dx, dy} != {0, 0}, do: {x + dx, y + dy}
  end

  @doc "The tile at `point`. Any coordinate with no tile, inside the level or out, is `:rock`."
  @spec at(t(), point()) :: tile()
  def at(%__MODULE__{tiles: tiles}, point), do: Map.get(tiles, point, :rock)

  @doc """
  Whether `point` can be stood on.

  True for `:floor`, `:door`, `:console` and `:stair`. A `:gate` is walkable only while the
  level is unsealed. `:rock` and `:wall` are never walkable.
  """
  @spec walkable?(t(), point()) :: boolean()
  def walkable?(%__MODULE__{} = level, point) do
    case at(level, point) do
      :floor -> true
      :door -> true
      :console -> true
      :stair -> true
      :gate -> level.unsealed?
      _other -> false
    end
  end

  @doc """
  Whether `point` lets sight through, as `Cauldron2D.Grid.Fov` asks it.

  True for everything except `:rock`, `:wall` and a `:door` not yet opened. This is not the
  inverse of `walkable?/2`:
  a sealed `:gate` blocks movement but not sight.
  """
  @spec transparent?(t(), point()) :: boolean()
  def transparent?(%__MODULE__{} = level, point) do
    at(level, point) not in [:rock, :wall, :door]
  end

  @doc "Every walkable tile, sorted, so the same level always yields the same list."
  @spec open_tiles(t()) :: [point()]
  def open_tiles(%__MODULE__{tiles: tiles} = level) do
    tiles
    |> Enum.filter(fn {point, _tile} -> walkable?(level, point) end)
    |> Enum.map(&elem(&1, 0))
    |> Enum.sort()
  end

  @doc """
  Open the gate: set `unsealed?` and turn the `:gate` tile into a `:stair`.

  Call this once the access code has been accepted; see `Scriber.Lattice.unseal/2`. A level
  with no gate is returned unchanged. Calling it twice is harmless.
  """
  @spec unseal(t()) :: t()
  def unseal(%__MODULE__{gate: nil} = level), do: level

  def unseal(%__MODULE__{} = level) do
    %{level | unsealed?: true, tiles: Map.put(level.tiles, level.gate, :stair)}
  end
end
